""" Configuration Variables """

MYSQL_DB_USERNAME = 'root'
MYSQL_DB_PASSWORD = 'root'
MYSQL_DB_HOSTNAME = 'localhost'
MYSQL_DB_NAME = 'flask_rest_db'

DEBUG = True
PORT = 5000
HOST = "127.0.0.1"

SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_ADDR}/{DB_NAME}" \
    .format(DB_USER=MYSQL_DB_USERNAME,
            DB_PASS=MYSQL_DB_PASSWORD,
            DB_ADDR=MYSQL_DB_HOSTNAME,
            DB_NAME=MYSQL_DB_NAME)

SECRET_KEY = "MERKY"

JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
